/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Martins
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuHospedes = new javax.swing.JMenu();
        nemuCadHospedes = new javax.swing.JMenuItem();
        nemuConHospedes = new javax.swing.JMenuItem();
        nemuQuartos = new javax.swing.JMenu();
        nemuCadQuartos = new javax.swing.JMenuItem();
        nemuConQuartos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        nemuReserva = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        nemuConsumo = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        nemuFinanceiro = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        nemuRelatorios = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        nemuSeguranca = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        nemuFerramentas = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastro.png"))); // NOI18N
        jMenu1.setText("Cadastros   |");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuHospedes.setText("Hospedes");

        nemuCadHospedes.setText("Cadastrar");
        menuHospedes.add(nemuCadHospedes);

        nemuConHospedes.setText("Consultar");
        menuHospedes.add(nemuConHospedes);

        jMenu1.add(menuHospedes);

        nemuQuartos.setText("Quartos");

        nemuCadQuartos.setText("Cadastrar");
        nemuQuartos.add(nemuCadQuartos);

        nemuConQuartos.setText("Consultar");
        nemuQuartos.add(nemuConQuartos);

        jMenu1.add(nemuQuartos);

        jMenu2.setText("Funcionários");
        jMenu1.add(jMenu2);

        jMenu3.setText("Fornecedores");
        jMenu1.add(jMenu3);

        jMenu4.setText("Produtos");
        jMenu1.add(jMenu4);

        jMenu5.setText("Serviços");
        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        nemuReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/reservas.png"))); // NOI18N
        nemuReserva.setText("Reservas   |");
        nemuReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu6.setText("Cadastrar Reserva");
        nemuReserva.add(jMenu6);

        jMenu7.setText("Consultar Reserva");
        nemuReserva.add(jMenu7);

        jMenu8.setText("Finalizar");
        nemuReserva.add(jMenu8);

        jMenuBar1.add(nemuReserva);

        nemuConsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consumo1.png"))); // NOI18N
        nemuConsumo.setText("Consumo   |");
        nemuConsumo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu9.setText("Produtos");
        nemuConsumo.add(jMenu9);

        jMenu10.setText("Serviços");
        nemuConsumo.add(jMenu10);

        jMenuBar1.add(nemuConsumo);

        nemuFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financeiro.png"))); // NOI18N
        nemuFinanceiro.setText("Financeiro   |");
        nemuFinanceiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu11.setText("Contas a Pagar");

        jMenuItem1.setText("Cadastrar");
        jMenu11.add(jMenuItem1);

        jMenuItem2.setText("Consultar");
        jMenu11.add(jMenuItem2);

        nemuFinanceiro.add(jMenu11);

        jMenu12.setText("Contas a Receber");
        nemuFinanceiro.add(jMenu12);

        jMenu13.setText("Balanço");
        nemuFinanceiro.add(jMenu13);

        jMenuBar1.add(nemuFinanceiro);

        nemuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorios.png"))); // NOI18N
        nemuRelatorios.setText("Relatórios   |");
        nemuRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu14.setText("Financeiro");

        jMenuItem6.setText("Contas a Pagar");
        jMenu14.add(jMenuItem6);

        jMenuItem7.setText("Contas a Receber");
        jMenu14.add(jMenuItem7);

        jMenuItem8.setText("Balanço");
        jMenu14.add(jMenuItem8);

        nemuRelatorios.add(jMenu14);

        jMenu15.setText("Reservas");
        nemuRelatorios.add(jMenu15);

        jMenu16.setText("Vendas");
        nemuRelatorios.add(jMenu16);

        jMenuItem3.setText("Hospedes");
        nemuRelatorios.add(jMenuItem3);

        jMenuItem4.setText("Funcionários");
        nemuRelatorios.add(jMenuItem4);

        jMenuItem5.setText("Fornecedores");
        nemuRelatorios.add(jMenuItem5);

        jMenuBar1.add(nemuRelatorios);

        nemuSeguranca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seguranca.png"))); // NOI18N
        nemuSeguranca.setText("Segurança   |");
        nemuSeguranca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem9.setText("Fazer Backup");
        nemuSeguranca.add(jMenuItem9);

        jMenuItem10.setText("Restaurar Backup");
        nemuSeguranca.add(jMenuItem10);

        jMenuBar1.add(nemuSeguranca);

        nemuFerramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ferramentas.png"))); // NOI18N
        nemuFerramentas.setText("Ferramentas   |");
        nemuFerramentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu17.setText("Tela de Fundo");

        jMenuItem11.setText("Add Imagem");
        jMenu17.add(jMenuItem11);

        jMenuItem13.setText("Remover Imagem");
        jMenu17.add(jMenuItem13);

        jMenuItem14.setText("Restaurar Padrão");
        jMenu17.add(jMenuItem14);

        nemuFerramentas.add(jMenu17);

        jMenuItem12.setText("Sobre o Sistema");
        nemuFerramentas.add(jMenuItem12);

        jMenuBar1.add(nemuFerramentas);

        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        menuSair.setText("Sair   |");
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuHospedes;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem nemuCadHospedes;
    private javax.swing.JMenuItem nemuCadQuartos;
    private javax.swing.JMenuItem nemuConHospedes;
    private javax.swing.JMenuItem nemuConQuartos;
    private javax.swing.JMenu nemuConsumo;
    private javax.swing.JMenu nemuFerramentas;
    private javax.swing.JMenu nemuFinanceiro;
    private javax.swing.JMenu nemuQuartos;
    private javax.swing.JMenu nemuRelatorios;
    private javax.swing.JMenu nemuReserva;
    private javax.swing.JMenu nemuSeguranca;
    // End of variables declaration//GEN-END:variables
}
